Some tests for SearchResultContainer and ResultsInfo component.
City-of-Helsinki/events-helsinki-ui pull request #276
Opened 2021-05-25 11:56 UTC by nikomakela

TH-1041 TH-1075 Added some tests for SearchResultContainer and ResultsInfo component.

2021-05-25 13:01 UTC, nikomakela commented
More related tests in #277

2021-05-28 05:55 UTC, Sartonon requested changes
Looks good but couple snapshot tests could be deleted and also use generic type to avoid type assertions.

2021-05-28 05:55 UTC, Sartonon commented on src/domain/eventSearch/searchResultList/__tests__/SearchResultsContainer.test.tsx
> +it.each([
Avoid type assertions:

`it.each<[number, EventType, string]>([`

2021-05-28 05:55 UTC, Sartonon commented on src/domain/eventSearch/searchResultList/__tests__/SearchResultsContainer.test.tsx
> +        eventType={eventType as EventType}
These type assertions can be deleted

2021-05-28 05:55 UTC, Sartonon commented on src/domain/eventSearch/searchResultList/__tests__/ResultsInfo.test.tsx
> +});
I think 1 snapshot test might be enough here

2021-05-31 07:19 UTC, merged